name: Update slow tests

on:
  schedule:
    # Every day at 5:05pm EDT
    - cron: "5 21 * * *"
  # Have the ability to trigger this job manually
  workflow_dispatch:

defaults:
  run:
    working-directory: torchci
jobs:
  update-slow-stats:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - run: yarn --silent node scripts/updateSlowTests.mjs > slow-tests.json
        env:
          ROCKSET_API_KEY: ${{ secrets.ROCKSET_API_KEY }}
      - name: Upload file to s3
        run: |
          python3 -mpip install awscli==1.27.69
          aws s3 cp "slow-tests.json" s3://ossci-metrics/slow-tests.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
