name: Update disabled tests

on:
  schedule:
    # Every 15 minutes
    - cron: "*/15 * * * *"
  # Have the ability to trigger this job manually through the API
  workflow_dispatch:
  pull_request:
    paths:
      - .github/scripts/update_disabled_issues.py

jobs:
  update-disabled-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate new disabled tests and jobs jsons
        env:
          # The token is used to confirm issue creator's write permission before
          # allowing them to disable jobs. Note that the token needs to have access
          # to the target repo, i.e. pytorch/pytorch instead of test-infra. Using
          # PyTorch bot token is the most obvious choice.
          GH_PYTORCHBOT_TOKEN: ${{ secrets.GH_PYTORCHBOT_TOKEN }}
        run: |
          python3 .github/scripts/update_disabled_issues.py

      - name: Print the list of disabled tests
        run: |
          cat disabled-tests-condensed.json

      - name: Print the list of disabled and unstable jobs
        run: |
          echo "Disabled jobs:"
          cat disabled-jobs.json

          echo
          echo "Unstable jobs:"
          cat unstable-jobs.json

      - name: Upload file to s3
        if: github.event_name != 'pull_request'
        run: |
          python3 -mpip install awscli==1.27.69

          aws s3 cp disabled-tests-condensed.json s3://ossci-metrics/disabled-tests-condensed.json
          aws s3 cp disabled-jobs.json s3://ossci-metrics/disabled-jobs.json
          aws s3 cp unstable-jobs.json s3://ossci-metrics/unstable-jobs.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
